// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    users,
    audioGenerationTasks,
    appSettings,
    serverBackends,
    peerConnections,
  ];
  late final Shape0 users = Shape0(
    source: i0.VersionedTable(
      entityName: 'users',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 audioGenerationTasks = Shape1(
    source: i0.VersionedTable(
      entityName: 'audio_generation_tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 appSettings = Shape2(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_38, _column_39],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 serverBackends = Shape3(
    source: i0.VersionedTable(
      entityName: 'server_backends',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 peerConnections = Shape4(
    source: i0.VersionedTable(
      entityName: 'peer_connections',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_1(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'created_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get model =>
      columnsByName['model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get taskType =>
      columnsByName['task_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get prompt =>
      columnsByName['prompt']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lyrics =>
      columnsByName['lyrics']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get negativePrompt =>
      columnsByName['negative_prompt']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get srcAudioPath =>
      columnsByName['src_audio_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get infillStart =>
      columnsByName['infill_start']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get infillEnd =>
      columnsByName['infill_end']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get stemName =>
      columnsByName['stem_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackClasses =>
      columnsByName['track_classes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get thinking =>
      columnsByName['thinking']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get constrainedDecoding =>
      columnsByName['constrained_decoding']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get guidanceScale =>
      columnsByName['guidance_scale']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get inferMethod =>
      columnsByName['infer_method']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get inferenceSteps =>
      columnsByName['inference_steps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get cfgIntervalStart =>
      columnsByName['cfg_interval_start']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get cfgIntervalEnd =>
      columnsByName['cfg_interval_end']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get shift =>
      columnsByName['shift']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get timeSignature =>
      columnsByName['time_signature']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get temperature =>
      columnsByName['temperature']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get cfgScale =>
      columnsByName['cfg_scale']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get topP =>
      columnsByName['top_p']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get repetitionPenalty =>
      columnsByName['repetition_penalty']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get audioDuration =>
      columnsByName['audio_duration']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get batchSize =>
      columnsByName['batch_size']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get useRandomSeed =>
      columnsByName['use_random_seed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get audioFormat =>
      columnsByName['audio_format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get taskId =>
      columnsByName['task_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get result =>
      columnsByName['result']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get error =>
      columnsByName['error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'model',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'task_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'prompt',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'lyrics',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'negative_prompt',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'src_audio_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_10(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'infill_start',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_11(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'infill_end',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'stem_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'track_classes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'thinking',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (thinking IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'constrained_decoding',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (constrained_decoding IN (0, 1))',
    );
i1.GeneratedColumn<double> _column_16(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'guidance_scale',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'infer_method',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'inference_steps',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_19(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'cfg_interval_start',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_20(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'cfg_interval_end',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_21(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'shift',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'time_signature',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_23(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'temperature',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_24(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'cfg_scale',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_25(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'top_p',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_26(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'repetition_penalty',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_27(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'audio_duration',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'batch_size',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'use_random_seed',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (use_random_seed IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'audio_format',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rating',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'task_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'result',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'error',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_37(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'completed_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: '',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get apiHost =>
      columnsByName['api_host']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get secure =>
      columnsByName['secure']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isActive =>
      columnsByName['is_active']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'api_host',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'secure',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT FALSE CHECK (secure IN (0, 1))',
      defaultValue: const i1.CustomExpression('FALSE'),
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_active',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT FALSE CHECK (is_active IN (0, 1))',
      defaultValue: const i1.CustomExpression('FALSE'),
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publicKey =>
      columnsByName['public_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get firstSeenAt =>
      columnsByName['first_seen_at']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lastSeenAt =>
      columnsByName['last_seen_at']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get requestCount =>
      columnsByName['request_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get blocked =>
      columnsByName['blocked']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'public_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<double> _column_45(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'first_seen_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: '',
    );
i1.GeneratedColumn<double> _column_46(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'last_seen_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'request_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'blocked',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT FALSE CHECK (blocked IN (0, 1))',
      defaultValue: const i1.CustomExpression('FALSE'),
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    users,
    audioGenerationTasks,
    appSettings,
    serverBackends,
    peerConnections,
    workspaces,
  ];
  late final Shape0 users = Shape0(
    source: i0.VersionedTable(
      entityName: 'users',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 audioGenerationTasks = Shape5(
    source: i0.VersionedTable(
      entityName: 'audio_generation_tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_49,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 appSettings = Shape2(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_38, _column_39],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 serverBackends = Shape3(
    source: i0.VersionedTable(
      entityName: 'server_backends',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 peerConnections = Shape4(
    source: i0.VersionedTable(
      entityName: 'peer_connections',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 workspaces = Shape6(
    source: i0.VersionedTable(
      entityName: 'workspaces',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_1, _column_2, _column_40, _column_50],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get model =>
      columnsByName['model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get taskType =>
      columnsByName['task_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get prompt =>
      columnsByName['prompt']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lyrics =>
      columnsByName['lyrics']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get negativePrompt =>
      columnsByName['negative_prompt']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get srcAudioPath =>
      columnsByName['src_audio_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get infillStart =>
      columnsByName['infill_start']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get infillEnd =>
      columnsByName['infill_end']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get stemName =>
      columnsByName['stem_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackClasses =>
      columnsByName['track_classes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get thinking =>
      columnsByName['thinking']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get constrainedDecoding =>
      columnsByName['constrained_decoding']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get guidanceScale =>
      columnsByName['guidance_scale']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get inferMethod =>
      columnsByName['infer_method']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get inferenceSteps =>
      columnsByName['inference_steps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get cfgIntervalStart =>
      columnsByName['cfg_interval_start']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get cfgIntervalEnd =>
      columnsByName['cfg_interval_end']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get shift =>
      columnsByName['shift']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get timeSignature =>
      columnsByName['time_signature']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get temperature =>
      columnsByName['temperature']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get cfgScale =>
      columnsByName['cfg_scale']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get topP =>
      columnsByName['top_p']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get repetitionPenalty =>
      columnsByName['repetition_penalty']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get audioDuration =>
      columnsByName['audio_duration']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get batchSize =>
      columnsByName['batch_size']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get useRandomSeed =>
      columnsByName['use_random_seed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get audioFormat =>
      columnsByName['audio_format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get workspaceId =>
      columnsByName['workspace_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get taskId =>
      columnsByName['task_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get result =>
      columnsByName['result']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get error =>
      columnsByName['error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'workspace_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isDefault =>
      columnsByName['is_default']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_default',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT FALSE CHECK (is_default IN (0, 1))',
      defaultValue: const i1.CustomExpression('FALSE'),
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'lyric_sheet_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: "NOT NULL DEFAULT ''",
      defaultValue: const i1.CustomExpression("''"),
    );

i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: "NOT NULL DEFAULT ''",
      defaultValue: const i1.CustomExpression("''"),
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get content =>
      columnsByName['content']! as i1.GeneratedColumn<String>;
}

// Shape8: audio_generation_tasks with lyric_sheet_id added
class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get model =>
      columnsByName['model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get taskType =>
      columnsByName['task_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get prompt =>
      columnsByName['prompt']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lyrics =>
      columnsByName['lyrics']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get negativePrompt =>
      columnsByName['negative_prompt']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get srcAudioPath =>
      columnsByName['src_audio_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get infillStart =>
      columnsByName['infill_start']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get infillEnd =>
      columnsByName['infill_end']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get stemName =>
      columnsByName['stem_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackClasses =>
      columnsByName['track_classes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get thinking =>
      columnsByName['thinking']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get constrainedDecoding =>
      columnsByName['constrained_decoding']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get guidanceScale =>
      columnsByName['guidance_scale']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get inferMethod =>
      columnsByName['infer_method']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get inferenceSteps =>
      columnsByName['inference_steps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get cfgIntervalStart =>
      columnsByName['cfg_interval_start']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get cfgIntervalEnd =>
      columnsByName['cfg_interval_end']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get shift =>
      columnsByName['shift']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get timeSignature =>
      columnsByName['time_signature']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get temperature =>
      columnsByName['temperature']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get cfgScale =>
      columnsByName['cfg_scale']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get topP =>
      columnsByName['top_p']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get repetitionPenalty =>
      columnsByName['repetition_penalty']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get audioDuration =>
      columnsByName['audio_duration']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get batchSize =>
      columnsByName['batch_size']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get useRandomSeed =>
      columnsByName['use_random_seed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get audioFormat =>
      columnsByName['audio_format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get workspaceId =>
      columnsByName['workspace_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lyricSheetId =>
      columnsByName['lyric_sheet_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get taskId =>
      columnsByName['task_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get result =>
      columnsByName['result']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get error =>
      columnsByName['error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<double>;
}

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    users,
    audioGenerationTasks,
    appSettings,
    serverBackends,
    peerConnections,
    workspaces,
    lyricSheets,
  ];
  late final Shape0 users = Shape0(
    source: i0.VersionedTable(
      entityName: 'users',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 audioGenerationTasks = Shape8(
    source: i0.VersionedTable(
      entityName: 'audio_generation_tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_49,
        _column_51,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 appSettings = Shape2(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_38, _column_39],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 serverBackends = Shape3(
    source: i0.VersionedTable(
      entityName: 'server_backends',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 peerConnections = Shape4(
    source: i0.VersionedTable(
      entityName: 'peer_connections',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 workspaces = Shape6(
    source: i0.VersionedTable(
      entityName: 'workspaces',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_1, _column_2, _column_40, _column_50],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 lyricSheets = Shape7(
    source: i0.VersionedTable(
      entityName: 'lyric_sheets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_1, _column_2, _column_52, _column_53],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3, from3To4: from3To4),
);
